### ISSUE TITLE
The register link is showing up even after linking

### ISSUE THREAD

**Issue by scarlet959** [mailerlite/wordpress-plugin#23]
The register link is showing up even after linking the plugin with an existing mailerlite a/c via API key

![image](https://user-images.githubusercontent.com/53694102/97077969-db9bcb00-1605-11eb-92e1-fa071b9d850e.png)

Plugin Version Used: 1.4.7
WordPress Version: 5.5.1

**Comment by llacle** [comment]
Closing issue as this has been fixed in version 1.5.0
